name: aistack
channels:
  - oxfordcontrol
  - fastai
  - pytorch
  - defaults
  - conda-forge
  - intel
  - gurobi
  - MOSEK
  - menpo
  - lukepfister
  - sbu-hpc
  - pyviz
dependencies:
  - absl-py=0.7.1
  - blas=1.0=mkl
  - boost-cpp=1.67
  - catboost=0.14.2
  - cudatoolkit=10.0.130
  - dask-core=1.2.0
  - dask=1.2.0
  - faiss-gpu=1.5.1
  - fastai=1.0.52
  - intel-openmp=2019
  - jupyterlab=0.35.5
  - libgpuarray=0.7.6
  - mkl-dnn=0.14
  - numba=0.43.1
  - numpy=1.16.3
  - osqp=0.5.0
  - pandas=0.24.2
  - pygpu=0.7.6
  - pymc=2.3.7.rc1
  - pymc3=3.6
  - pyqt=5
  - python=3.6
  - pytorch=1.0.1
  - qt=5
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - statsmodels=0.9
  - tensorflow-gpu=1.13
  - tensorflow-estimator=1.13
  - theano=1.0.4
  - torchvision=0.2.2
  - _ipyw_jlab_nb_ext_conf
  - ad3-cpp
  - aenum
  - affine
  - alabaster
  - alembic
  - amqp
  - ansiwrap
  - appdirs
  - apscheduler
  - argcomplete
  - argh
  - arrow
  - asn1crypto
  - aspy.yaml
  - asteval
  - astor
  - astroid
  - astropy
  - atomicwrites
  - attrdict
  - attrs
  - automat
  - autopep8
  - babel
  - backcall
  - backports
  - backports.shutil_get_terminal_size
  - bcolz
  - bcrypt
  - beautifulsoup4
  - billiard
  - bitarray
  - bkcharts
  - black
  - blaze
  - bleach
  - blessings
  - blosc
  - bokeh
  - boto
  - boto3
  - botocore
  - bottleneck
  - bqplot
  - bumpversion
  - bzip2
  - cached-property
  - cairo
  - cartopy
  - celery
  - certifi
  - cffi
  - cfgv
  - chardet
  - click
  - click-plugins
  - cliff
  - cloudpickle
  - clyent
  - cmarkgfm
  - cmd2
  - codecov
  - colorama
  - colorlog
  - colorlover
  - configparser
  - constantly
  - contextlib2
  - coverage
  - coveralls
  - crcmod
  - cryptography
  - cryptography-vectors
  - cuda100
  - cupti
  - cycler
  - cymem
  - cython
  - cytoolz
  - daal
  - daal4py
  - dask-ml
  - dataclasses
  - datashape
  - dbfread
  - debtcollector
  - decorator
  - defusedxml
  - deprecation
  - dill
  - diskcache
  - distributed
  - django
  - django-extensions
  - dnspython
  - docker-pycreds
  - docopt
  - docutils
  - docx2txt
  - doit
  - dominate
  - eigen
  - emcee
  - entrypoints
  - et_xmlfile
  - execnet
  - expat
  - faker
  - fastcache
  - fasteners
  - fastnumbers
  - fastparquet
  - fastprogress
  - fastrlock
  - feather-format
  - fftw
  - filelock
  - fire
  - flake8
  - flask
  - flask-cors
  - flask-sqlalchemy
  - freetype
  - fribidi
  - ftfy
  - future
  - gast
  - gensim
  - get_terminal_size
  - gettext
  - gevent
  - giflib
  - gitdb2
  - gitpython
  - glfw3
  - glib
  - glob2
  - glove
  - gmp
  - gmpy2
  - gperftools
  - gql
  - graphite2
  - graphql-core
  - graphql-relay
  - graphql-server-core
  - greenlet
  - griddataformats
  - grpcio
  - gsd
  - gsl
  - gst-plugins-base
  - gstreamer
  - gunicorn
  - gurobi
  - h5netcdf
  - h5py
  - hdf5
  - heapdict
  - holoviews
  - html5lib
  - httplib2
  - hyperlink
  - icc_rt
  - icu
  - identify
  - idna
  - ijson
  - imagehash
  - imageio
  - imagesize
  - incremental
  - intervals
  - invoke
  - ipdb
  - ipp
  - ipp-include
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipyvolume
  - ipywebrtc
  - ipywidgets
  - iso8601
  - isort
  - itsdangerous
  - jasper
  - jbig
  - jdcal
  - jedi
  - jeepney
  - jinja2
  - jmespath
  - joblib
  - jsondiff
  - jsonpickle
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterlab_launcher
  - jupyterlab_server
  - kealib
  - kiwisolver
  - kombu
  - lazy-object-proxy
  - libarchive
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libnetcdf
  - libpng
  - librosa
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtool
  - libwebp
  - libxcb
  - libxml2
  - libxslt
  - livereload
  - llvmlite
  - lmdb
  - locket
  - lockfile
  - luigi
  - lxml
  - lz4
  - lz4-c
  - lzo
  - m2r
  - magma-cuda100
  - mahotas
  - mako
  - markdown
  - markupsafe
  - matplotlib
  - maven
  - mccabe
  - memory_profiler
  - metakernel
  - metis
  - mistune
  - mkl
  - mkl-devel
  - mkl-include
  - mkl-service
  - mkl_fft
  - mkl_random
  - mmtf-python
  - mock
  - more-itertools
  - mosek
  - moto
  - moviepy
  - mpc
  - mpfr
  - mpl-probscale
  - mpmath
  - msgpack-numpy
  - msgpack-python
  - multipledispatch
  - munch
  - murmurhash
  - mypy
  - mypy_extensions
  - mysql-connector-python
  - mysqlclient
  - namedlist
  - natsort
  - nbconvert
  - nbformat
  - nbsphinx
  - nbstripout
  - nbtutor
  - nbval
  - nccl2
  - ncurses
  - netaddr
  - netcdf4
  - netifaces
  - networkx
  - nibabel
  - ninja
  - nltk
  - nodeenv
  - nose
  - nose2
  - notebook
  - numexpr
  - numpydoc
  - oct2py
  - octave_kernel
  - odfpy
  - odo
  - olefile
  - opencv
  - openpyxl
  - openssl
  - ordered-set
  - oslo.config
  - oslo.i18n
  - oslo.utils
  - overrides
  - packaging
  - pandoc
  - pandocfilters
  - param
  - paramiko
  - paramz
  - parmetis
  - parquet-cpp
  - parso
  - partd
  - patchelf
  - path.py
  - pathlib2
  - pathtools
  - patsy
  - pbr
  - pcre
  - pdbpp
  - pdfminer3k
  - peewee
  - pep8
  - pep8-naming
  - pexpect
  - pickleshare
  - pillow
  - pint
  - pip
  - pixman
  - plotly
  - plotnine
  - pluggy
  - plumbum
  - ply
  - portpicker
  - posix_ipc
  - preshed
  - prettytable
  - progressbar2
  - prometheus_client
  - promise
  - prompt_toolkit
  - protobuf
  - prov
  - psutil
  - psycopg2
  - ptyprocess
  - pulp
  - py
  - py4j
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pyaudio
  - pybind11
  - pycodestyle
  - pycosat
  - pycparser
  - pycrypto
  - pycuda
  - pydot
  - pydotplus
  - pyemd
  - pyfftw
  - pyflakes
  - pygments
  - pyinotify
  - pylint
  - pymongo
  - pymysql
  - pynacl
  - pynfft
  - pyomo
  - pyomo.extras
  - pyopengl
  - pyopenssl
  - pypandoc
  - pyparsing
  - pyperclip
  - pyqtgraph
  - pyro4
  - pysal
  - pyscaffold
  - pyserial
  - pysftp
  - pysocks
  - pyspark
  - pytables
  - pytest
  - pytest-arraydiff
  - pytest-astropy
  - pytest-cov
  - pytest-doctestplus
  - pytest-mock
  - pytest-openfiles
  - pytest-remotedata
  - pytest-runner
  - pytest-timeout
  - pytest-xdist
  - python-annoy
  - python-crfsuite
  - python-dateutil
  - python-gflags
  - python-igraph
  - python-libarchive-c
  - python-lmdb
  - python-magic
  - python-slugify
  - pytoml
  - pytools
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qtawesome
  - qtconsole
  - qtpy
  - quantities
  - quaternion
  - rdflib
  - readline
  - recommonmark
  - redis
  - rednose
  - regex
  - reportlab
  - requests
  - requests-oauthlib
  - requests-toolbelt
  - resampy
  - rfc3986
  - rope
  - rply
  - rpy2
  - ruamel_yaml
  - rx
  - s3fs
  - s3transfer
  - scandir
  - scikit-image
  - scikit-mdr
  - scikit-optimize
  - scrapy
  - seaborn
  - secretstorage
  - selenium
  - semantic_version
  - send2trash
  - sentinels
  - sentry-sdk
  - serpent
  - service_identity
  - setuptools
  - setuptools-git
  - setuptools_scm
  - shapely
  - shortuuid
  - simhash
  - simplegeneric
  - simplejson
  - singledispatch
  - sip
  - six
  - sk-video
  - sklearn-contrib-lightning
  - skrebate
  - smart_open
  - smmap2
  - smp
  - snakeviz
  - snowballstemmer
  - sortedcollections
  - sortedcontainers
  - sox
  - spacy
  - sparsehash
  - spectrum
  - sphinx
  - sphinx-autobuild
  - sphinx_rtd_theme
  - sphinxcontrib
  - sphinxcontrib-websupport
  - spyder-kernels
  - sqlalchemy
  - sqlite
  - stevedore
  - sympy
  - tabulate
  - tbb
  - tbb4py
  - tblib
  - tensorboard
  - termcolor
  - terminado
  - testfixtures
  - testpath
  - thinc
  - thrift
  - thrift-cpp
  - thriftpy
  - tinydb
  - tk
  - toml
  - toolz
  - tornado
  - tox
  - tqdm
  - traitlets
  - traits
  - traittypes
  - tweepy
  - twine
  - twisted
  - typing
  - typing-extensions
  - ujson
  - uncertainties
  - unicodecsv
  - unidecode
  - unixodbc
  - urllib3
  - urwid
  - util-linux
  - validate_email
  - vcrpy
  - vine
  - virtualenv
  - watchdog
  - wcwidth
  - webencodings
  - websocket-client
  - websockets
  - werkzeug
  - wheel
  - whichcraft
  - widgetsnbextension
  - wikipedia
  - wmctrl
  - wrapt
  - xarray
  - xerces-c
  - xlrd
  - xlsxwriter
  - xlwt
  - xmltodict
  - xz
  - yaml
  - yapf
  - zeromq
  - zict
  - zlib
  - zope
  - zope.interface
  - zstd
